config/routes.rb
Rails.application.routes.draw do

	root to: 'articles#index'

  resources :articles do
  	resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	
  def index
  	@articles = Article.all
  end

  def show
  	@article = Article.find(params[:id])
  	@comment = Comment.new
  	@comment.article_id = @article.id
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
  	@article.save

		flash.notice = "Article #{@article.title} Created!"

  	redirect_to article_path(@article)
  end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		flash.notice = "Article #{@article.title} Deleted!"

		redirect_to articles_path
	end  

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article #{@article.title} Updated!"

		redirect_to article_path(@article)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]

		@comment.save

		redirect_to article_path(@comment.article)
	end

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_comments.html.erb
<div>
	<h4>Comment by <%= comments.author_name %></h4>
	<p class="comment"><%= comments.body %></p>
	<p>
		Posted <%= distance_of_time_in_words(comments.article.created_at, comments.created_at) %> after article
	</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
	<ul>
	<% @article.errors.full_messages.each do |error| %>
		<li>
			<%= error %>
		</li>
	<% end %>
	</ul>
	
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>

	</ul>
<%end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render partial: "form" %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles" >
	<% @articles.each do |article| %>
		<li><a href=""><%= link_to article.title, article_path(article), class: "article_title" %></a></li>
	<% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: "form" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>


<p><%= @article.body %></p>
<br>
<p>
	<%= link_to "Edit Post", edit_article_path(@article) %>
</p>
<p>
	<%= link_to "Delete Post", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}
 %>
</p>
<br>
<h3>Comments (<%= @article.comments.count %>)</h3>
<%= render partial: "articles/comments", collection: @article.comments %>

<%= render partial: "comments/form" %>

<br>
<%= link_to "<< Back to Articles List", articles_path %>

app/views/comments/_form.html.erb
<h3>Post a comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
	<ul>
		<% @comment.errors.full_messages.each do |error| %>
			<%= error %>
		<% end %>
	</ul>
	
	<p>
		<%= f.label :author_name, "Your name" %><br>
		<%= f.text_field :author_name %>
	</p>

	<p>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash">
	<%= flash.notice %>
</p>

<%= yield %>

</body>
</html>